# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f79c203f7afb3bf2bcb0d804b226d5041f6e54fd8882c4028f7f113e762d6d0fbaf0a42c5349ed6864342be7965b3fdaa20135317896da77ac0c28db780e97b2

test:
  secret_key_base: ea6be09370c3362680cd69a46e62c7923f2b196ebaca8630de6db2099d732fca4f2485d3c0dc1345cc28dde3c6162ff199cff6e87759ae43a47d908a6eac8b0c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
